"""Update cascade

Revision ID: 6088364fdb08
Revises: a023415d2100
Create Date: 2023-06-23 14:27:40.510465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6088364fdb08'
down_revision = 'a023415d2100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_books_cover_id_images', 'books', type_='foreignkey')
    op.create_foreign_key(op.f('fk_books_cover_id_images'), 'books', 'images', ['cover_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('fk_books_genres_book_id_books', 'books_genres', type_='foreignkey')
    op.drop_constraint('fk_books_genres_genre_id_genres', 'books_genres', type_='foreignkey')
    op.create_foreign_key(op.f('fk_books_genres_book_id_books'), 'books_genres', 'books', ['book_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_books_genres_genre_id_genres'), 'books_genres', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_books_genres_genre_id_genres'), 'books_genres', type_='foreignkey')
    op.drop_constraint(op.f('fk_books_genres_book_id_books'), 'books_genres', type_='foreignkey')
    op.create_foreign_key('fk_books_genres_genre_id_genres', 'books_genres', 'genres', ['genre_id'], ['id'])
    op.create_foreign_key('fk_books_genres_book_id_books', 'books_genres', 'books', ['book_id'], ['id'])
    op.drop_constraint(op.f('fk_books_cover_id_images'), 'books', type_='foreignkey')
    op.create_foreign_key('fk_books_cover_id_images', 'books', 'images', ['cover_id'], ['id'])
    # ### end Alembic commands ###
